# 파이썬 기반의 머신러닝과 생태계 이해 

## 01. 머신러닝 개념

## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지 

## 03. numpy

In [3]:
#넘파이 개요 
import numpy as np 

#넘파이의 배열 
array1=np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태: ', array1.shape)

array2= np.array([[1,2,3,],[2,3,4]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2.shape)

array3 = np.array([[1,2,3]])
print('array type : ', type(array3))
print('array3 array 형태 :', array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array type :  <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [4]:
#array ndim을 이용해 확인 
print('array1: {:0}차원, array2 :{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2 :2차원, array3: 2차원


In [22]:
#ndarray의 데이터타입
list1=[1,2,3]
print(type(list1),'\n')

array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype,'\n')

#다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype,'\n')

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype,'\n')

<class 'list'> 

<class 'numpy.ndarray'>
[1 2 3] int64 

['1' '2' 'test'] <U21 

[1. 2. 3.] float64 



In [21]:
#stype()매서드를 이용한 ndarray 데이터 값 변경 
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype,'\n')

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype,'\n')

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype,'\n')

[1. 2. 3.] float64 

[1 2 3] int32 

[1 2 3] int32 



In [20]:
#ndarray 편리하게 생성하기 - arange, zeros, ones 

#arange - 0부터 인자 -1 값까지 순차적으로 변환
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape,'\n')

#zeros() and ones() - 모든 값은 0혹은 1로 채운 shape을 가진 ndarray 반환
zero_array=np.zeros((3,2), dtype=('int32'))
print(zero_array)
print(zero_array.dtype,zero_array.shape,'\n')

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape,'\n')

[0 1 2 3 4 5 6 7 8 9]
int64 (10,) 

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2) 



In [24]:
#ndarray의 차원과 크기를 변경하는 reshape()

array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3 :\n',array3)

#지정된 사이즈로 변경 불가능할 때 error
array1.reshape(4,3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [26]:
#reshape 효율적으로 사용하기 - 인자를 -1로 적용하기 
# >> 원래 ndarray와 호환되는 새로운 shape로 변환
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)
